log-level: "debug"

database:
  driver: mysql
  name: "orders"
  host: "localhost"
  port: 3306
  user: "root"
  password: "root"

rest-server:
  port: "3000"

grpc-service:
  port: "50051"

graph-server:
  port: "8080"